sudo: false
language: python
addons:
  postgresql: "9.4"
python:
  - "2.7"
cache:
  directories:
    - node_modules
install:
  - make develop dev-postgres
before_script:
  - psql -c "create database lemur;" -U postgres
  - psql -c "create user lemur with password 'lemur;'" -U postgres
  - npm install -g bower
script:
  - make lint
  - make test

notifications:
  email:
    kglisson@netflix.com