sudo: false
language: python
services:
  - postgresql
python:
  - "2.7"
cache:
  directories:
    - node_modules
    - .pip_download_cache
    - "$HOME/virtualenv/python2.7.9"
env:
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"
install:
  - time make develop dev-postgres
before_script:
  - psql -c 'create database lemur;' -U postgres
script:
  - make lint
  - make test-js
  - py.test tests
  - make test-cli

notifications:
  email:
    kglisson@netflix.com